;;5. PRENDER Y APAGAR UN LED CONECTADO AL PUERTO B MEDIANTE UN INTERRUPTOR CONECTADO EN EL PUERTO C.
__CONFIG _CONFIG1, _LVP_OFF & _FCMEN_ON & _IESO_ON & _BOR_ON & _CPD_OFF & _CP_OFF & _MCLRE_ON & _PWRTE_ON & _WDT_OFF & _XT_OSC
__CONFIG _CONFIG2, _WRT_OFF & _BOR40V

LIST P = 16F887
#include <P16F887.INC>

ORG 0X00
ORG 0x04

Inicio
	banksel	ANSEL
	clrf	ANSEL
	clrf	ANSELH
	
	banksel TRISC            
	movlw	b'00000001'
	movwf	TRISC
	clrf	TRISB
	banksel PORTB

Bucle
	movf	PORTC, 0
	movwf	PORTB
	goto	Bucle
	end